name: Form e2e integration tests on canonical.com
on:
  # TODO: Remove after QA. The tests should run as a CRON and not on individual PRs.
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - "templates/**"
  schedule:
    - cron: "20 7 * * *"
env:
  SECRET_KEY: insecure_test_key

jobs:
  test-marketo-form-generator:
    if: github.repository == 'canonical/canonical.com'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Marketo tests
        env:
          MARKETO_API_URL: "https://066-EOV-335.mktorest.com"
          MARKETO_API_CLIENT: ${{ secrets.MARKETO_API_CLIENT }}
          MARKETO_API_SECRET: ${{ secrets.MARKETO_API_SECRET }}

        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 -m unittest tests.test_marketo
