name: Marketo Tests for form-generator
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test-marketo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Marketo tests
        env:
          MARKETO_API_URL: "https://066-EOV-335.mktorest.com"
          MARKETO_API_CLIENT: ${{ secrets.FLASK_MARKETO_API_CLIENT }}
          MARKETO_API_SECRET: ${{ secrets.FLASK_MARKETO_API_SECRET }}
        run: |
          pwd
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 -m unittest tests.test_marketo
